import {
  Activity,
  PersonalBest,
  UserProfile,
  LeaderboardEntry,
  RankHistoryEntry,
  WeeklyStats,
  WorkoutLog,
  Milestone,
  RaceGoal,
  WeeklyVolume,
  TrainingPlan,
  DisciplineAvailability,
  SocialProfile,
  FriendLeaderboardEntry,
  ConnectedDevice,
} from "@/types";

export const mockUser: UserProfile = {
  id: "user-001",
  email: "alex@iron3.app",
  displayName: "Alex Rivera",
  avatarUrl: null,
  experienceLevel: "intermediate",
  goals: ["Complete Olympic Triathlon", "Sub 20min 5k"],
  isPremium: true,
  createdAt: "2025-06-01T00:00:00Z",
  athleteType: "experienced",
  raceDistanceGoal: "half_ironman",
  targetRaceDate: "2026-05-07T00:00:00Z",
  preferredMode: "performance_focused",
  swimLevel: "comfortable",
  bikeLevel: "strong",
  runLevel: "comfortable",
  weeklyAvailability: "4-5",
  primaryGoal: "improve_time",
  age: 32,
};

export const mockActivities: Activity[] = [
  {
    id: "act-001",
    userId: "user-001",
    discipline: "swim",
    date: "2026-03-26T07:00:00Z",
    distance: 1500,
    duration: 1620,
    pace: 108,
    pointsEarned: 225,
    distanceBonus: 75,
    paceBonus: 0,
    title: "Morning Pool Session",
    createdAt: "2026-03-26T08:30:00Z",
  },
  {
    id: "act-002",
    userId: "user-001",
    discipline: "bike",
    date: "2026-03-25T16:00:00Z",
    distance: 45,
    duration: 5400,
    pace: 120,
    pointsEarned: 265,
    distanceBonus: 40,
    paceBonus: 0,
    title: "Evening Road Ride",
    createdAt: "2026-03-25T18:00:00Z",
  },
  {
    id: "act-003",
    userId: "user-001",
    discipline: "run",
    date: "2026-03-24T06:30:00Z",
    distance: 10,
    duration: 2880,
    pace: 288,
    pointsEarned: 160,
    distanceBonus: 40,
    paceBonus: 50,
    title: "Tempo 10K",
    createdAt: "2026-03-24T07:30:00Z",
  },
  {
    id: "act-004",
    userId: "user-001",
    discipline: "swim",
    date: "2026-03-23T07:30:00Z",
    distance: 2000,
    duration: 2400,
    pace: 120,
    pointsEarned: 320,
    distanceBonus: 120,
    paceBonus: 0,
    title: "Endurance Swim",
    createdAt: "2026-03-23T09:00:00Z",
  },
  {
    id: "act-005",
    userId: "user-001",
    discipline: "run",
    date: "2026-03-22T17:00:00Z",
    distance: 5,
    duration: 1320,
    pace: 264,
    pointsEarned: 155,
    distanceBonus: 15,
    paceBonus: 100,
    title: "Fast 5K",
    createdAt: "2026-03-22T17:30:00Z",
  },
  {
    id: "act-006",
    userId: "user-001",
    discipline: "bike",
    date: "2026-03-21T09:00:00Z",
    distance: 80,
    duration: 9000,
    pace: 112.5,
    pointsEarned: 520,
    distanceBonus: 120,
    paceBonus: 0,
    title: "Long Weekend Ride",
    createdAt: "2026-03-21T12:00:00Z",
  },
  {
    id: "act-007",
    userId: "user-001",
    discipline: "swim",
    date: "2026-03-20T06:00:00Z",
    distance: 1000,
    duration: 960,
    pace: 96,
    pointsEarned: 215,
    distanceBonus: 40,
    paceBonus: 75,
    title: "Speed Drills",
    createdAt: "2026-03-20T07:00:00Z",
  },
  {
    id: "act-008",
    userId: "user-001",
    discipline: "run",
    date: "2026-03-19T18:00:00Z",
    distance: 15,
    duration: 5400,
    pace: 360,
    pointsEarned: 195,
    distanceBonus: 75,
    paceBonus: 0,
    title: "Easy Long Run",
    createdAt: "2026-03-19T19:30:00Z",
  },
];

export const mockPersonalBests: PersonalBest[] = [
  { discipline: "swim", category: "100m", value: 78, unit: "sec", date: "2026-02-15" },
  { discipline: "swim", category: "400m", value: 360, unit: "sec", date: "2026-01-20" },
  { discipline: "swim", category: "1500m", value: 1560, unit: "sec", date: "2025-12-10" },
  { discipline: "bike", category: "20km", value: 2160, unit: "sec", date: "2026-03-01" },
  { discipline: "bike", category: "40km", value: 4500, unit: "sec", date: "2026-02-20" },
  { discipline: "bike", category: "100km", value: 12600, unit: "sec", date: "2025-11-15" },
  { discipline: "run", category: "5km", value: 1260, unit: "sec", date: "2026-03-10" },
  { discipline: "run", category: "10km", value: 2760, unit: "sec", date: "2026-02-28" },
  { discipline: "run", category: "Half Marathon", value: 6300, unit: "sec", date: "2025-10-05" },
];

export const mockSwimPoints = 3450;
export const mockBikePoints = 5280;
export const mockRunPoints = 4120;

export const mockLeaderboard: LeaderboardEntry[] = [
  { rank: 1, userId: "u-010", displayName: "Marcus Chen", avatarUrl: null, points: 15200, tier: "Diamond", tierColor: "#B9F2FF", isFriend: false },
  { rank: 2, userId: "u-011", displayName: "Sarah Kimura", avatarUrl: null, points: 12800, tier: "Platinum", tierColor: "#B0C4DE", isFriend: true },
  { rank: 3, userId: "u-012", displayName: "Diego Ramirez", avatarUrl: null, points: 11450, tier: "Platinum", tierColor: "#B0C4DE", isFriend: false },
  { rank: 4, userId: "u-013", displayName: "Emma Walsh", avatarUrl: null, points: 9870, tier: "Gold", tierColor: "#FFD700", isFriend: true },
  { rank: 5, userId: "u-014", displayName: "Kai Nakamura", avatarUrl: null, points: 8650, tier: "Gold", tierColor: "#FFD700", isFriend: false },
  { rank: 6, userId: "user-001", displayName: "Alex Rivera", avatarUrl: null, points: 4350, tier: "Silver", tierColor: "#C0C0C0", isFriend: false },
  { rank: 7, userId: "u-015", displayName: "Lena Mueller", avatarUrl: null, points: 4100, tier: "Silver", tierColor: "#C0C0C0", isFriend: true },
  { rank: 8, userId: "u-016", displayName: "Jake Turner", avatarUrl: null, points: 3800, tier: "Silver", tierColor: "#C0C0C0", isFriend: false },
  { rank: 9, userId: "u-017", displayName: "Priya Sharma", avatarUrl: null, points: 2200, tier: "Bronze", tierColor: "#CD7F32", isFriend: true },
  { rank: 10, userId: "u-018", displayName: "Chris Lang", avatarUrl: null, points: 1650, tier: "Bronze", tierColor: "#CD7F32", isFriend: false },
];

export const mockRankHistory: RankHistoryEntry[] = [
  { date: "2025-10-01", swimPoints: 200, bikePoints: 350, runPoints: 180, overallPoints: 260 },
  { date: "2025-11-01", swimPoints: 600, bikePoints: 980, runPoints: 520, overallPoints: 720 },
  { date: "2025-12-01", swimPoints: 1100, bikePoints: 1800, runPoints: 1050, overallPoints: 1370 },
  { date: "2026-01-01", swimPoints: 1850, bikePoints: 2900, runPoints: 1800, overallPoints: 2255 },
  { date: "2026-02-01", swimPoints: 2700, bikePoints: 4100, runPoints: 3050, overallPoints: 3365 },
  { date: "2026-03-01", swimPoints: 3450, bikePoints: 5280, runPoints: 4120, overallPoints: 4359 },
];

export const mockWeeklyStats: WeeklyStats = {
  swimDistance: 4500,
  bikeDistance: 125,
  runDistance: 30,
  totalActivities: 8,
  totalPoints: 1555,
};

export const mockWorkoutLogs: WorkoutLog[] = [
  {
    id: "wl-001",
    userId: "user-001",
    discipline: "swim",
    workoutType: "endurance",
    duration: 1620,
    distance: 1500,
    effort: 6,
    indoorOutdoor: "indoor",
    notes: "Felt great, consistent pace throughout",
    pointsEarned: 225,
    date: "2026-03-26T07:00:00Z",
    createdAt: "2026-03-26T08:30:00Z",
  },
  {
    id: "wl-002",
    userId: "user-001",
    discipline: "bike",
    workoutType: "endurance",
    duration: 5400,
    distance: 45,
    effort: 7,
    indoorOutdoor: "outdoor",
    notes: "",
    pointsEarned: 265,
    date: "2026-03-25T16:00:00Z",
    createdAt: "2026-03-25T18:00:00Z",
  },
  {
    id: "wl-003",
    userId: "user-001",
    discipline: "run",
    workoutType: "tempo",
    duration: 2880,
    distance: 10,
    effort: 8,
    indoorOutdoor: "outdoor",
    notes: "Pushed the pace, new PB zone",
    pointsEarned: 160,
    date: "2026-03-24T06:30:00Z",
    createdAt: "2026-03-24T07:30:00Z",
  },
  {
    id: "wl-004",
    userId: "user-001",
    discipline: "strength",
    workoutType: "core",
    duration: 1800,
    distance: null,
    effort: 5,
    indoorOutdoor: null,
    notes: "Planks, Russian twists, dead bugs",
    pointsEarned: 50,
    date: "2026-03-23T18:00:00Z",
    createdAt: "2026-03-23T18:30:00Z",
  },
  {
    id: "wl-005",
    userId: "user-001",
    discipline: "brick",
    workoutType: "bike_to_run",
    duration: 5400,
    distance: null,
    effort: 9,
    indoorOutdoor: "outdoor",
    notes: "40km bike then 5km run, legs felt heavy",
    pointsEarned: 350,
    date: "2026-03-21T09:00:00Z",
    createdAt: "2026-03-21T11:00:00Z",
  },
];

export const mockMilestones: Milestone[] = [
  {
    id: "ms-001",
    type: "first_workout",
    title: "First Workout Logged",
    description: "You logged your very first workout!",
    achievedAt: "2025-06-02T10:00:00Z",
    icon: "🎯",
  },
  {
    id: "ms-002",
    type: "first_swim",
    title: "First Swim",
    description: "Your first swim session is in the books!",
    achievedAt: "2025-06-02T10:00:00Z",
    icon: "🏊",
  },
  {
    id: "ms-003",
    type: "first_bike",
    title: "First Bike Ride",
    description: "You hit the road on two wheels!",
    achievedAt: "2025-06-05T10:00:00Z",
    icon: "🚴",
  },
  {
    id: "ms-004",
    type: "first_run",
    title: "First Run",
    description: "Your first run is logged!",
    achievedAt: "2025-06-07T10:00:00Z",
    icon: "🏃",
  },
  {
    id: "ms-005",
    type: "streak_7",
    title: "7-Day Streak",
    description: "You trained 7 days in a row!",
    achievedAt: "2025-07-15T10:00:00Z",
    icon: "🔥",
  },
  {
    id: "ms-006",
    type: "streak_30",
    title: "30-Day Streak",
    description: "An incredible 30-day training streak!",
    achievedAt: "2025-09-01T10:00:00Z",
    icon: "💪",
  },
  {
    id: "ms-007",
    type: "rank_up_bronze",
    title: "Reached Bronze",
    description: "You climbed to Bronze rank!",
    achievedAt: "2025-08-15T10:00:00Z",
    icon: "🥉",
  },
  {
    id: "ms-008",
    type: "rank_up_silver",
    title: "Reached Silver",
    description: "Silver rank achieved!",
    achievedAt: "2025-12-01T10:00:00Z",
    icon: "🥈",
  },
  {
    id: "ms-009",
    type: "sessions_10",
    title: "10 Sessions",
    description: "You completed 10 training sessions!",
    achievedAt: "2025-07-01T10:00:00Z",
    icon: "📊",
  },
  {
    id: "ms-010",
    type: "sessions_50",
    title: "50 Sessions",
    description: "50 sessions in the books!",
    achievedAt: "2025-11-20T10:00:00Z",
    icon: "📈",
  },
  {
    id: "ms-011",
    type: "balanced_week",
    title: "Balanced Week",
    description: "Trained all 3 disciplines in one week!",
    achievedAt: "2025-08-01T10:00:00Z",
    icon: "⚖️",
  },
  {
    id: "ms-012",
    type: "hours_50",
    title: "50 Hours Trained",
    description: "50 hours of total training!",
    achievedAt: "2025-10-15T10:00:00Z",
    icon: "⏱️",
  },
  {
    id: "ms-013",
    type: "sessions_100",
    title: "100 Sessions",
    description: "Triple digits! 100 sessions complete!",
    achievedAt: null,
    icon: "🏆",
  },
  {
    id: "ms-014",
    type: "rank_up_gold",
    title: "Reached Gold",
    description: "Gold rank! You're among the top athletes.",
    achievedAt: null,
    icon: "🥇",
  },
  {
    id: "ms-015",
    type: "hours_100",
    title: "100 Hours Trained",
    description: "100 hours of dedication!",
    achievedAt: null,
    icon: "🕐",
  },
];

export const mockRaceGoal: RaceGoal = {
  id: "rg-001",
  raceType: "half_ironman",
  raceName: "Ironman 70.3",
  raceDate: "2026-05-07T00:00:00Z",
  goalType: "finish",
};

export const mockWeeklyVolumes: WeeklyVolume[] = [
  { week: "W1 Mar", swimHours: 2.5, bikeHours: 4.0, runHours: 3.0 },
  { week: "W2 Mar", swimHours: 3.0, bikeHours: 3.5, runHours: 2.5 },
  { week: "W3 Mar", swimHours: 2.0, bikeHours: 5.0, runHours: 3.5 },
  { week: "W4 Mar", swimHours: 2.8, bikeHours: 4.5, runHours: 2.0 },
];

// Training Plan mock data (Task 3)
export const mockTrainingPlan: TrainingPlan = {
  name: "PREP plan",
  currentWeek: 1,
  totalWeeks: 20,
  phase: "BASE",
  weeklyPlan: [
    { day: "MON", discipline: "bike", title: "1 hr Easy Ride", duration: 60, distance: 22.4, completed: true, actualDuration: 63, actualDistance: 24.9 },
    { day: "TUE", discipline: "swim", title: "Breathing Rhythm Intro (10x50)", duration: 19, distance: 0.5, completed: true, actualDuration: 22, actualDistance: 0.5 },
    { day: "WED", discipline: "run", title: "1 hr 30 min Long Run", duration: 90, distance: null, completed: false },
    { day: "THU", discipline: "rest", title: "Rest Day", duration: 0, distance: null, completed: true },
    { day: "FRI", discipline: "swim", title: "Technique Drills (8x100)", duration: 35, distance: 0.8, completed: false },
    { day: "SAT", discipline: "bike", title: "2 hr Endurance Ride", duration: 120, distance: 48, completed: false },
    { day: "SUN", discipline: "run", title: "45 min Easy Run", duration: 45, distance: 7, completed: false },
  ],
};

// Availability mock data (Task 4)
export const mockAvailability: DisciplineAvailability = {
  swim: ["TUE", "THU", "SAT"],
  bike: ["MON", "WED", "SAT"],
  run: ["TUE", "WED", "FRI", "SUN"],
  preferredLongRideDay: "SAT",
};

// Social Profile mock data (Task 6)
export const mockSocialProfile: SocialProfile = {
  followers: 431,
  following: 77,
  bio: "24 - Running for 3 months. Obsessed with getting faster.",
  weeklyDistance: 28.73,
  weeklyTime: 261,
  weeklyElevation: 331,
  rrChange: 66,
};

// Friends Leaderboard mock data (Task 7)
export const mockFriendsLeaderboard: FriendLeaderboardEntry[] = [
  { rank: 1, userId: "u-020", displayName: "Marcus Chen", avatarUrl: null, points: 15200, tier: "Diamond", tierColor: "#22D3EE", isFriend: true, avatarLetter: "M" },
  { rank: 2, userId: "u-021", displayName: "Sarah Kimura", avatarUrl: null, points: 12800, tier: "Platinum", tierColor: "#818CF8", isFriend: true, avatarLetter: "S" },
  { rank: 3, userId: "u-022", displayName: "Diego Ramirez", avatarUrl: null, points: 11450, tier: "Platinum", tierColor: "#818CF8", isFriend: true, avatarLetter: "D" },
  { rank: 4, userId: "u-023", displayName: "Emma Walsh", avatarUrl: null, points: 9870, tier: "Gold", tierColor: "#F59E0B", isFriend: true, avatarLetter: "E" },
  { rank: 5, userId: "u-024", displayName: "Kai Nakamura", avatarUrl: null, points: 8650, tier: "Gold", tierColor: "#F59E0B", isFriend: true, avatarLetter: "K" },
  { rank: 6, userId: "user-001", displayName: "Alex Rivera", avatarUrl: null, points: 4350, tier: "Silver", tierColor: "#94A3B8", isFriend: false, avatarLetter: "A" },
  { rank: 7, userId: "u-025", displayName: "Lena Mueller", avatarUrl: null, points: 4100, tier: "Silver", tierColor: "#94A3B8", isFriend: true, avatarLetter: "L" },
  { rank: 8, userId: "u-026", displayName: "Jake Turner", avatarUrl: null, points: 3800, tier: "Silver", tierColor: "#94A3B8", isFriend: true, avatarLetter: "J" },
  { rank: 9, userId: "u-027", displayName: "Priya Sharma", avatarUrl: null, points: 2200, tier: "Bronze", tierColor: "#D97706", isFriend: true, avatarLetter: "P" },
  { rank: 10, userId: "u-028", displayName: "Chris Lang", avatarUrl: null, points: 1650, tier: "Bronze", tierColor: "#CD7F32", isFriend: true, avatarLetter: "C" },
];

// Connected Devices mock data (Task 8)
export const mockConnectedDevices: ConnectedDevice[] = [
  { id: "dev-001", name: "Apple Health", type: "apple_health", isConnected: false, lastSync: null },
  { id: "dev-002", name: "Garmin Connect", type: "garmin", isConnected: false, lastSync: null },
  { id: "dev-003", name: "Strava", type: "strava", isConnected: false, lastSync: null },
];

export const MOTIVATIONAL_MESSAGES = [
  "Every session counts. Keep showing up.",
  "Consistency beats intensity. You're building something great.",
  "The race is won in training. Stay the course.",
  "Your future self will thank you for today's effort.",
  "Progress isn't always linear, but it's always forward.",
  "Swim. Bike. Run. Repeat. That's how legends are made.",
  "You're not just training — you're transforming.",
  "One more session closer to your goal.",
];
